name = "Telegraph-Image"
compatibility_date = "2024-01-01"

[build]
command = ""
watch_dir = ""

[[kv_namespaces]]
binding = "img_url"
id = ""

[[r2_buckets]]
binding = "img_r2"
bucket_name = ""
preview_bucket_name = ""

[[d1_databases]]
binding = "img_db"
database_name = ""
database_id = ""
